print("hello " + "world")
print("hello " * 3)
print("hello"[0])
print("hello"[-1])
print("hello world"[0:5])
print("hello world"[:5])
print("hello world"[0:])
print("hello world"[6:100])
print("hello world"[0:-1])